#!/bin/bash

#How to define an Array?

myarray=( 1 2 30.5 Hello "Hey man!")

#How to get values from an array?

echo "value is ${myarray[0]}"
echo "${myarray[1]}"

#How to get length of array?
echo "${#myarray[*]}"

#How to get specific values?
echo "${myarray[*]:1}"
echo "${myarray[*]:1:2}"

#How to update an array?
myarray+=( 5 6 8 "Hello")

echo "Values of new array are ${myarray[*]}"
