#!/bin/bash

#<<<comment

#echo "Hey choose an option"
#echo "a = To see the current date"
#echo "b = list all the files in current dir"
#read choice
#case $choice in
#a) date;;
#b) ls;;
#*) echo "Non a valid input"
ہے
#esac

#comment


echo "Provide an option"
echo "a for print date"
echo "b for list of scripts"
echo "c to check the current location"


read choice

case $choice in 
	a)	echo "Today's date is :"
	date
		echo "Ending"
	;;
	b)ls;;
	c)pwd;;
	*)echo "please provide a valid value"
	
esac
